version: "3.5"

services:
  assets:
    image: flashspys/nginx-static
    ports:
    - 8080:80
    volumes:
    - ./application/public:/static

  web:
    image: bref/fpm-dev-gateway
    ports:
    - 80:80
    volumes:
    - .:/var/task
    depends_on:
    - php
    environment:
      HANDLER: application/public/index.php

  php:
    image: bref/php-73-fpm-dev
    volumes:
    - .:/var/task:ro

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./data/mysql/:/var/lib/mysql
    ports:
    - 3306:3306

  redis:
    image: redis:4.0.11-alpine
    volumes:
    - ./data/redis:/data
