FROM bref/fpm-dev-gateway

# install groupadd
RUN yum -y install unzip shadow-utils.x86_64

# https://vsupalov.com/docker-shared-permissions/
ARG USER_ID
ARG GROUP_ID
RUN /usr/sbin/groupadd --gid $GROUP_ID user
RUN /usr/sbin/useradd --uid $USER_ID --gid $GROUP_ID user
USER user