version: "3.5"

services:
  assets:
    image: flashspys/nginx-static
    ports:
    - 8080:80
    volumes:
    - ./application/public:/static

  web:
    image: bref/fpm-dev-gateway
    ports:
    - 8000:80
    volumes:
    - .:/var/task:ro
    depends_on:
    - php
    environment:
      HANDLER: application/public/index.php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        USER_ID: ${CURRENT_USER_ID}
        GROUP_ID: ${CURRENT_GROUP_ID}
    image: php
    # provide aws creds to env for serverless to use
    env_file: 
      - ./.aws_creds
      - ./application/.env.local
    volumes:
      - type: bind
        source: ./
        target: /var/task
      - serverless_reading_list-home_npm_dir:/home/user/.npm

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - serverless_reading_list-mysql:/var/lib/mysql
    ports:
    - 3306:3306

  redis:
    image: redis:4.0.11-alpine
    volumes:
    - serverless_reading_list-redis:/data

volumes:
  serverless_reading_list-mysql:
  serverless_reading_list-redis:
  serverless_reading_list-home_npm_dir: