version: "3.5"

services:
  assets:
    image: flashspys/nginx-static
    ports:
      - 8080:80
    volumes:
      - ./frontend:/static

  web:
    image: bref/fpm-dev-gateway
    ports:
      - 8000:80
    volumes:
      - .:/var/task:ro
    depends_on:
      - php
    environment:
      HANDLER: application/public/index.php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        USER_ID: ${CURRENT_USER_ID}
        GROUP_ID: ${CURRENT_GROUP_ID}
    image: php
    ports:
      - 8040:8080
      - 8030:8000
      - 4000:4000
    # provide aws creds to env for serverless to use
    env_file:
      - ./.aws_creds
      - ./application/.env.local
    volumes:
      - type: bind
        source: ./
        target: /var/task
      - home_npm:/home/user/.npm

  mysql:
    image: mysql:5.7.33
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:4.0.11-alpine
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
  home_npm:
